In [1]:
#import packages
import pandas as pd
import csv
import os
import numpy as np
from sqlalchemy import create_engine

In [4]:
#import tsv file into df 
#kids_df = pd.read_csv('kids_teen.tsv',delimiter='\t',encoding='utf-8')

#import KIDS & TEEN cvs file
csv_file = "Resources/kids_teen.csv"
kids_df = pd.read_csv(csv_file)

kids_df.describe()
kids_df.head()

,round,value,daily_double,category,comments,answer,question,air_date,notes
0,1,100,no,BIRDS,-,The bat parrot probably got its name from slee...,upside-down,2/16/1987,1987 Teen Tournament quarterfinal game 1.
1,1,200,no,BIRDS,-,"Too ""lei""zy to migrate, the geese in this trop...",Hawaii,2/16/1987,1987 Teen Tournament quarterfinal game 1.
2,1,300,no,BIRDS,-,A bird waterproofs its feathers with oil from ...,its tail,2/16/1987,1987 Teen Tournament quarterfinal game 1.
3,1,100,no,THE LIBRARY,-,Defacing books or shouting or throwing spitbal...,three activities prohibited in the library,2/16/1987,1987 Teen Tournament quarterfinal game 1.
4,1,200,no,THE LIBRARY,-,"On most reference books in your local library,...",R,2/16/1987,1987 Teen Tournament quarterfinal game 1.

In [5]:
#import second tsv file into df 
#master_df = pd.read_csv('master_season1-35.tsv',delimiter='\t',encoding='utf-8')

#import MASTER 1 TO 35seasons cvs file
csv_file_2 = "Resources/master_season.csv"
master_df = pd.read_csv(csv_file_2)

master_df.describe()
master_df.head()

,round,value,daily_double,category,comments,answer,question,air_date,notes
0,1,100,no,LAKES & RIVERS,-,River mentioned most often in the Bible,the Jordan,9/10/1984,-
1,1,200,no,LAKES & RIVERS,-,Scottish word for lake,loch,9/10/1984,-
2,1,400,no,LAKES & RIVERS,-,American river only 33 miles shorter than the ...,the Missouri,9/10/1984,-
3,1,500,no,LAKES & RIVERS,-,"World's largest lake, nearly 5 times as big as...",the Caspian Sea,9/10/1984,-
4,1,100,no,INVENTIONS,-,Marconi's wonderful wireless,the radio,9/10/1984,-

In [6]:
#exploratory#
print(master_df['category'].value_counts())
print(master_df['air_date'].value_counts())

SCIENCE                     860
LITERATURE                  814
AMERICAN HISTORY            788
HISTORY                     720
SPORTS                      701
                           ...
QUOTATIONS ABOUT LAWYERS      1
THE NUCLEAR AGE               1
WORLD TIME ZONES              1
MUSIC IN AMERICA              1
POP MUSIC MILESTONES          1
Name: category, Length: 43352, dtype: int64
7/19/1999     61
6/15/1998     61
1/27/2005     61
11/14/1994    61
9/29/1997     61
              ..
2/25/1986     15
6/12/1990     14
1/29/1993      8
5/25/1990      1
6/30/1989      1
Name: air_date, Length: 6297, dtype: int64

In [7]:
#exploratory#
print(kids_df['category'].value_counts())
print(kids_df['air_date'].value_counts())

STATE CAPITALS             97
AMERICAN HISTORY           78
AMERICAN LITERATURE        73
BODIES OF WATER            72
WORLD CAPITALS             71
                           ..
FICTIONAL BEINGS            1
19th CENTURY INVENTIONS     1
GEOGRAPHIC SUPERLATIVES     1
EARLY AMERICA               1
INTERNATIONAL GROUPS        1
Name: category, Length: 3303, dtype: int64
9/10/1999     61
5/8/1996      61
11/11/1997    61
2/7/2003      61
2/13/1997     61
              ..
9/25/2001     45
12/2/2014     45
9/27/2001     44
10/12/2005    42
10/22/2004    41
Name: air_date, Length: 370, dtype: int64

In [8]:
#Add binary column for kids_jeopardy delegation#
kids_df['kids_jeopardy'] = 0
master_df['kids_jeopardy'] = 1

In [13]:
# append two data sets into one file #
jeopardy_df = kids_df.append(master_df) 
jeopardy_df.head(50)

,round,value,daily_double,category,comments,answer,question,air_date,notes,kids_jeopardy
0,1,100,no,BIRDS,-,The bat parrot probably got its name from slee...,upside-down,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
1,1,200,no,BIRDS,-,"Too ""lei""zy to migrate, the geese in this trop...",Hawaii,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
2,1,300,no,BIRDS,-,A bird waterproofs its feathers with oil from ...,its tail,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
3,1,100,no,THE LIBRARY,-,Defacing books or shouting or throwing spitbal...,three activities prohibited in the library,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
4,1,200,no,THE LIBRARY,-,"On most reference books in your local library,...",R,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
5,1,300,no,THE LIBRARY,-,When a book has been checked out it's said to ...,circulation,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
6,1,400,no,THE LIBRARY,-,"In this classification system, WWII, 940.54, c...",the Dewey Decimal system,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
7,1,500,no,THE LIBRARY,-,Shirley Jones played this part by the book in ...,(Marian the) librarian,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
8,1,100,no,LEAD SINGERS,-,Genesis,Phil Collins,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
9,1,200,no,LEAD SINGERS,-,The Police,Sting,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
10,1,300,no,LEAD SINGERS,-,Wham!,George Michael,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
11,1,400,no,LEAD SINGERS,-,Eurythmics,Annie Lennox,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
12,1,500,no,LEAD SINGERS,-,Talking Heads,David Byrne,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
13,1,100,no,PLAYTIME,-,"To compete with ""G.I. Joe"", Coleco has created...",Rambo,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
14,1,200,no,PLAYTIME,-,"In 1977, Kenner sold gift certificates for toy...",Star Wars,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
15,1,300,no,PLAYTIME,-,Christmas stockings in 1986 were filled with t...,Rubik,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
16,1,400,no,PLAYTIME,-,"Since 1949, this game manufacturer has sold ab...",Milton Bradley,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
17,1,500,no,PLAYTIME,-,A battle of the bands is ensuing between Barbi...,Jem,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
18,1,100,no,CURRENT EVENTS,-,"Hamilton, Ohio recently added this punctuation...",an exclamation mark,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
19,1,200,no,CURRENT EVENTS,-,"\""Hands Across America"" raised money for the h...",the United States of America,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
20,1,300,no,CURRENT EVENTS,-,"In October 1986, Reagan & Gorbachev went face ...",Reykjavik,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
21,1,200,yes,CURRENT EVENTS,-,"Father Lawrence Jenco, the Reverend Benjamin W...",hostages that were released from Beirut,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
22,1,500,no,CURRENT EVENTS,-,"In 1986, for the 1st time ever, 2 women ran ag...",Nebraska,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
23,1,100,no,CAR TALK,-,"If you ""boil the hides"", it means your rear ti...",smoke,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
24,1,200,no,CAR TALK,-,"When fixing cars, ""R & R"" means remove & do th...",restore (or replace or repair),2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
25,1,300,no,CAR TALK,-,"When your car is ""on the hook"", it's traveling...",on a tow truck,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
26,1,400,no,CAR TALK,-,"When a car has been ""chopped"", this part of it...",the top,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
27,2,200,no,LITERATURE,-,"Death of his son led him to write a ""History o...",(Sir Arthur Conan) Doyle,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
28,2,400,no,LITERATURE,-,"\""A Christmas Carol"" character who tells Scroo...",Jacob Marley,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
29,2,800,no,LITERATURE,-,"19th c. feminist Catharine Beecher wrote ""The ...",Harriet Beecher Stowe,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
30,2,1000,no,LITERATURE,-,"Subtitled ""A Tale of Acadie"", this Longfellow ...",Evangeline,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
31,2,200,no,THE WORLD,-,"On the 1st day of spring or fall, the Sun is d...",the Equator,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
32,2,400,no,THE WORLD,-,"Of about 10, 30, or 50%, percentage of Earth's...",30%,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
33,2,600,no,THE WORLD,-,All of the peoples of the world belong to this...,Homo sapiens,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
34,2,800,no,THE WORLD,-,Guinness says more people emigrate from this L...,Mexico,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
35,2,1000,no,THE WORLD,-,"The term ""second world"" refers to this nation ...",the Soviet Union,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
36,2,200,no,TEEN QUEENS,-,This teenage Egyptian ruler gave birth to a so...,Cleopatra,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
37,2,400,no,TEEN QUEENS,-,"Teen-aged Mary, Queen of Scots, also became qu...",France,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
38,2,600,no,TEEN QUEENS,-,"At 15, she became the future Louis XVI's bride...",Marie Antoinette,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
39,2,800,no,TEEN QUEENS,-,"British monarch crowned in 1837, when she was ...",Victoria,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
40,2,1000,no,TEEN QUEENS,-,Many claim that before Bloody Mary grabbed the...,Lady Jane Grey,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
41,2,200,no,QUOTES,-,"Ben Franklin said, ""There was never a good war...",peace,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
42,2,400,no,QUOTES,-,It was way back in 1696 that Mary Manley wrote...,the present,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
43,2,1000,yes,QUOTES,-,"Penguin's Modern Quotes lists ""Supercalifragil...",Disney,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
44,2,800,no,QUOTES,-,17th century English diarist known for the phr...,Samuel Pepys,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
45,2,1000,no,QUOTES,-,"Bartlett's says she ""coined"" the phrase ""equal...",Susan B. Anthony,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
46,2,200,no,AMERICAN HOLIDAYS,-,"Since 1941, Thanksgiving is observed on this T...",the fourth Thursday,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
47,2,400,no,AMERICAN HOLIDAYS,-,"\""Shrove Tuesday"", the day before Lent starts,...",Mardi Gras,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
48,2,600,no,AMERICAN HOLIDAYS,-,Supposedly a union president suggested date of...,Labor Day,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0
49,2,800,no,AMERICAN HOLIDAYS,-,"Until June 1, 1954, this was officially called...",Veterans Day,2/16/1987,1987 Teen Tournament quarterfinal game 1.,0

In [15]:
#drop irrelevant columns in dataframe#
jeopardy_df = jeopardy_df[['round', 'value', 'category', 'answer', 'question', 'air_date', 'kids_jeopardy']].copy()

#rename value column to point_value
jeopardy_df['point_value']= jeopardy_df['value']
jeopardy_df.head(50)

,round,value,category,answer,question,air_date,kids_jeopardy,point_value
0,1,100,BIRDS,The bat parrot probably got its name from slee...,upside-down,2/16/1987,0,100
1,1,200,BIRDS,"Too ""lei""zy to migrate, the geese in this trop...",Hawaii,2/16/1987,0,200
2,1,300,BIRDS,A bird waterproofs its feathers with oil from ...,its tail,2/16/1987,0,300
3,1,100,THE LIBRARY,Defacing books or shouting or throwing spitbal...,three activities prohibited in the library,2/16/1987,0,100
4,1,200,THE LIBRARY,"On most reference books in your local library,...",R,2/16/1987,0,200
5,1,300,THE LIBRARY,When a book has been checked out it's said to ...,circulation,2/16/1987,0,300
6,1,400,THE LIBRARY,"In this classification system, WWII, 940.54, c...",the Dewey Decimal system,2/16/1987,0,400
7,1,500,THE LIBRARY,Shirley Jones played this part by the book in ...,(Marian the) librarian,2/16/1987,0,500
8,1,100,LEAD SINGERS,Genesis,Phil Collins,2/16/1987,0,100
9,1,200,LEAD SINGERS,The Police,Sting,2/16/1987,0,200
10,1,300,LEAD SINGERS,Wham!,George Michael,2/16/1987,0,300
11,1,400,LEAD SINGERS,Eurythmics,Annie Lennox,2/16/1987,0,400
12,1,500,LEAD SINGERS,Talking Heads,David Byrne,2/16/1987,0,500
13,1,100,PLAYTIME,"To compete with ""G.I. Joe"", Coleco has created...",Rambo,2/16/1987,0,100
14,1,200,PLAYTIME,"In 1977, Kenner sold gift certificates for toy...",Star Wars,2/16/1987,0,200
15,1,300,PLAYTIME,Christmas stockings in 1986 were filled with t...,Rubik,2/16/1987,0,300
16,1,400,PLAYTIME,"Since 1949, this game manufacturer has sold ab...",Milton Bradley,2/16/1987,0,400
17,1,500,PLAYTIME,A battle of the bands is ensuing between Barbi...,Jem,2/16/1987,0,500
18,1,100,CURRENT EVENTS,"Hamilton, Ohio recently added this punctuation...",an exclamation mark,2/16/1987,0,100
19,1,200,CURRENT EVENTS,"\""Hands Across America"" raised money for the h...",the United States of America,2/16/1987,0,200
20,1,300,CURRENT EVENTS,"In October 1986, Reagan & Gorbachev went face ...",Reykjavik,2/16/1987,0,300
21,1,200,CURRENT EVENTS,"Father Lawrence Jenco, the Reverend Benjamin W...",hostages that were released from Beirut,2/16/1987,0,200
22,1,500,CURRENT EVENTS,"In 1986, for the 1st time ever, 2 women ran ag...",Nebraska,2/16/1987,0,500
23,1,100,CAR TALK,"If you ""boil the hides"", it means your rear ti...",smoke,2/16/1987,0,100
24,1,200,CAR TALK,"When fixing cars, ""R & R"" means remove & do th...",restore (or replace or repair),2/16/1987,0,200
25,1,300,CAR TALK,"When your car is ""on the hook"", it's traveling...",on a tow truck,2/16/1987,0,300
26,1,400,CAR TALK,"When a car has been ""chopped"", this part of it...",the top,2/16/1987,0,400
27,2,200,LITERATURE,"Death of his son led him to write a ""History o...",(Sir Arthur Conan) Doyle,2/16/1987,0,200
28,2,400,LITERATURE,"\""A Christmas Carol"" character who tells Scroo...",Jacob Marley,2/16/1987,0,400
29,2,800,LITERATURE,"19th c. feminist Catharine Beecher wrote ""The ...",Harriet Beecher Stowe,2/16/1987,0,800
30,2,1000,LITERATURE,"Subtitled ""A Tale of Acadie"", this Longfellow ...",Evangeline,2/16/1987,0,1000
31,2,200,THE WORLD,"On the 1st day of spring or fall, the Sun is d...",the Equator,2/16/1987,0,200
32,2,400,THE WORLD,"Of about 10, 30, or 50%, percentage of Earth's...",30%,2/16/1987,0,400
33,2,600,THE WORLD,All of the peoples of the world belong to this...,Homo sapiens,2/16/1987,0,600
34,2,800,THE WORLD,Guinness says more people emigrate from this L...,Mexico,2/16/1987,0,800
35,2,1000,THE WORLD,"The term ""second world"" refers to this nation ...",the Soviet Union,2/16/1987,0,1000
36,2,200,TEEN QUEENS,This teenage Egyptian ruler gave birth to a so...,Cleopatra,2/16/1987,0,200
37,2,400,TEEN QUEENS,"Teen-aged Mary, Queen of Scots, also became qu...",France,2/16/1987,0,400
38,2,600,TEEN QUEENS,"At 15, she became the future Louis XVI's bride...",Marie Antoinette,2/16/1987,0,600
39,2,800,TEEN QUEENS,"British monarch crowned in 1837, when she was ...",Victoria,2/16/1987,0,800
40,2,1000,TEEN QUEENS,Many claim that before Bloody Mary grabbed the...,Lady Jane Grey,2/16/1987,0,1000
41,2,200,QUOTES,"Ben Franklin said, ""There was never a good war...",peace,2/16/1987,0,200
42,2,400,QUOTES,It was way back in 1696 that Mary Manley wrote...,the present,2/16/1987,0,400
43,2,1000,QUOTES,"Penguin's Modern Quotes lists ""Supercalifragil...",Disney,2/16/1987,0,1000
44,2,800,QUOTES,17th century English diarist known for the phr...,Samuel Pepys,2/16/1987,0,800
45,2,1000,QUOTES,"Bartlett's says she ""coined"" the phrase ""equal...",Susan B. Anthony,2/16/1987,0,1000
46,2,200,AMERICAN HOLIDAYS,"Since 1941, Thanksgiving is observed on this T...",the fourth Thursday,2/16/1987,0,200
47,2,400,AMERICAN HOLIDAYS,"\""Shrove Tuesday"", the day before Lent starts,...",Mardi Gras,2/16/1987,0,400
48,2,600,AMERICAN HOLIDAYS,Supposedly a union president suggested date of...,Labor Day,2/16/1987,0,600
49,2,800,AMERICAN HOLIDAYS,"Until June 1, 1954, this was officially called...",Veterans Day,2/16/1987,0,800

In [ ]:
#connect to PostgreSQL#
rds_connection_string = "postgres:postgres@localhost:5432/customer_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [ ]:
#################AFTER TABLE CREATION IN POSTGRES###############################

#check table names# 
engine.table_names()

In [ ]:
#add data to PostgreSQL
jeopardy_df.to_sql(name='jeopardy_table', con=engine, if_exists='append', index=False)

In [ ]:
#Check data with a query
pd.read_sql_query('select * from jeopardy_table', con=engine).head()